import type { NextPage } from "next"
import Head from "next/head"
import { Title } from "@mantine/core"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title>psalut</Title>
      <p>Hello world!</p>
    </div>
  )
}
export default Home
